import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import './globals.css';
import SessionWrapper from "@/app/provider/SessionWrapper";
import HeaderMobileOne from "@/components/Header/headerMobileOne";
import HeaderDesktop from "@/components/Header/headerDesktop";
import React from "react";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionWrapper>

            {children}

        </SessionWrapper>
        </body>
        </html>
    );
}
